name: nonsense
favicon: null
layout_spectrum: 0.7311623424757272
typography_spectrum: 0.5545891744550318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.056779307778924704
  lightness: 0.6581879234872758
  saturation: 0.0827151364646852
  rhythmicContrast: 0.40880418941378593
purpose: []
